//
// Created by lyn on 2023/3/2.
//

#ifndef NUTS_NUTS_SERVER_REGISTER_H
#define NUTS_NUTS_SERVER_REGISTER_H

#define NUTS_SERVER_REGISTER_LEVEL_PSM 1
#define NUTS_SERVER_REGISTER_LEVEL_PATH 2
#define NUTS_SERVER_REGISTER_LEVEL_API 3

#endif //NUTS_NUTS_SERVER_REGISTER_H
